=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/module.dtd
<!ENTITY % phpType "bool | int | float | string | array | resource | object | mixed">

<!ELEMENT module (class | function)*>
<!ELEMENT class (function*)>
<!ELEMENT function (param*, alias*)>
<!ELEMENT alias EMPTY>
<!ELEMENT param EMPTY>

<!ATTLIST module
			earlyInit (false | true) "false">
<!ATTLIST class
			name CDATA #REQUIRED
			arrayGetter CDATA #IMPLIED
			arraySetter CDATA #IMPLIED
      description CDATA #IMPLIED>
<!ATTLIST function
			name CDATA #REQUIRED
			returnType (%phpType; | void) "mixed"
			static (false | true) "false"
			castToFalse (false | true) "false"
			marshalBoundVars (none | in | out | inout) "none"
			description CDATA #IMPLIED>
<!ATTLIST alias
      name CDATA #REQUIRED>
<!ATTLIST param
			name CDATA #IMPLIED
			type (%phpType;) "mixed"
			bind (false | true) "false"
			direction (in | out | inout) "in"
			optional (false | true | vararg) "false">

=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/php_zip.php5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="void" name="zip_close" description="Closes the given ZIP file archive.">
    <param type="resource" name="zip" />
  </function>
  <function returnType="bool" name="zip_entry_close" description="Closes the specified directory entry.">
    <param type="resource" name="zip_entry" />
  </function>
  <function returnType="int" name="zip_entry_compressedsize" description="Returns the compressed size of the specified directory entry.">
    <param type="resource" name="zip_entry" />
  </function>
  <function returnType="string" name="zip_entry_compressionmethod" description="Returns the compression method of the directory entry specified by zip_entry.">
    <param type="resource" name="zip_entry" />
  </function>
  <function returnType="int" name="zip_entry_filesize" description="Returns the actual size of the specified directory entry.">
    <param type="resource" name="zip_entry" />
  </function>
  <function returnType="string" name="zip_entry_name" description="Returns the name of the specified directory entry.">
    <param type="resource" name="zip_entry" />
  </function>
  <function returnType="bool" name="zip_entry_open" description="Opens a directory entry in a zip file for reading.">
    <param type="resource" name="zip" />
    <param type="resource" name="zip_entry" />
    <param type="string" name="mode" optional="true" />
  </function>
  <function returnType="string" name="zip_entry_read" description="Reads from an open directory entry.">
    <param type="resource" name="zip_entry" />
    <param type="int" name="length" optional="true" />
  </function>
  <function returnType="mixed" castToFalse="true" name="zip_open" description="Opens a new zip archive for reading.">
    <param type="string" name="filename" />
  </function>
  <function returnType="mixed" castToFalse="true" name="zip_read" description="Reads the next entry in a zip file archive.">
    <param type="resource" name="zip" />
  </function>
  <class name="ZipArchive" description="A ZIP archive class.">
    <function returnType="bool" name="addEmptyDir" description="Adds an empty directory in the archive.">
      <param type="string" name="dirname" />
    </function>
    <function returnType="bool" name="addFile" description="Adds a file to a ZIP archive from a given path.">
      <param type="string" name="filename" />
      <param type="string" name="localname" optional="true" />
    </function>
    <function returnType="bool" name="addFromString" description="Adds a file to a ZIP archive using its contents.">
      <param type="string" name="localname" />
      <param type="string" name="contents" />
    </function>
    <function returnType="bool" name="close" description="Close opened or created archive and save changes. This method is automatically called at the end of the script.">
    </function>
    <function returnType="bool" name="deleteIndex" description="Delete an entry in the archive using its index.">
      <param type="int" name="index" />
    </function>
    <function returnType="bool" name="deleteName" description="Delete an entry in the archive using its name.">
      <param type="string" name="name" />
    </function>
    <function returnType="bool" name="extractTo" description="Extract the complete archive or the given files to the specified destination.">
      <param type="string" name="destination" />
      <param type="mixed" name="entries" optional="true" />
    </function>
    <function returnType="string" name="getArchiveComment" description="Returns the Zip archive comment.">
    </function>
    <function returnType="string" name="getCommentIndex" description="Returns the comment of an entry using the entry index.">
      <param type="int" name="index" />
      <param type="int" name="flags" optional="true" />
    </function>
    <function returnType="string" name="getCommentName" description="Returns the comment of an entry using the entry name.">
      <param type="string" name="name" />
      <param type="int" name="flags" optional="true" />
    </function>
    <function returnType="mixed" name="getFromIndex" description="Returns the entry contents using its index.">
      <param type="int" name="index" />
      <param type="int" name="flags" optional="true" />
    </function>
    <function returnType="mixed" name="getFromName" description="Returns the entry contents using its name.">
      <param type="string" name="name" />
      <param type="int" name="flags" optional="true" />
    </function>
    <function returnType="string" name="getNameIndex" description="Returns the name of an entry using its index.">
      <param type="int" name="index" />
    </function>
    <function returnType="string" name="getStatusString" description="Returns the status error message, system and/or zip messages.">
    </function>
    <function returnType="resource" name="getStream" description="Get a file handler to the entry defined by its name. For now it only supports read operations.">
      <param type="string" name="name" />
    </function>
    <function returnType="mixed" name="locateName" description="Locates an entry using its name.">
      <param type="string" name="name" />
      <param type="int" name="flags" optional="true" />
    </function>
    <function returnType="mixed" name="open" description="Opens a new zip archive for reading, writing or modifying.">
      <param type="string" name="filename" />
      <param type="int" name="flags" optional="true" />
    </function>
    <function returnType="bool" name="renameIndex" description="Renames an entry defined by its index.">
      <param type="int" name="index" />
      <param type="int" name="newname" />
    </function>
    <function returnType="bool" name="renameName" description="Renames an entry defined by its name.">
      <param type="string" name="name" />
      <param type="int" name="newname" />
    </function>
    <function returnType="mixed" name="setArchiveComment" description="Set the comment of a ZIP archive.">
      <param type="string" name="name" />
    </function>
    <function returnType="mixed" name="setCommentIndex" description="Set the comment of an entry defined by its index.">
      <param type="int" name="index" />
      <param type="string" name="comment" />
    </function>
    <function returnType="mixed" name="setCommentName" description="Set the comment of an entry defined by its name.">
      <param type="string" name="name" />
      <param type="string" name="comment" />
    </function>
    <function returnType="mixed" name="statIndex" description="The function obtains information about the entry defined by its index.">
      <param type="int" name="index" />
      <param type="int" name="flags" optional="true" />
    </function>
    <function returnType="mixed" name="statIndex" description="The function obtains information about the entry defined by its name.">
      <param type="string" name="name" />
      <param type="int" name="flags" optional="true" />
    </function>
    <function returnType="mixed" name="unchangeAll" description="Undo all changes done in the archive.">
    </function>
    <function returnType="mixed" name="unchangeArchive" description="Revert all global changes to the archive. For now, this only reverts archive comment changes.">
    </function>
    <function returnType="mixed" name="unchangeIndex" description="Revert all changes done to an entry at the given index.">
        <param type="int" name="index" />
    </function>
    <function returnType="mixed" name="unchangeName" description="Revert all changes done to an entry.">
        <param type="string" name="name" />
    </function>
  </class>
</module>

=== d3sformal/weverca/External Sources/PhalangerOriginal/Deployment/TypeDefs/php_xmlrpc.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="array" name="xmlrpc_decode_request" description="Decodes XML into native PHP types.">
    <param type="string" name="xml" />
    <param type="string" name="method" />
    <param optional="true" type="string" name="encoding" />
  </function>
  <function returnType="array" name="xmlrpc_decode" description="Decodes XML into native PHP types.">
    <param type="string" name="xml" />
    <param optional="true" type="string" name="encoding" />
  </function>
  <function returnType="string" name="xmlrpc_encode" description="Generates XML for a PHP value.">
    <param type="mixed" name="value" />
  </function>
  <function returnType="bool" name="xmlrpc_server_register_method" description="Register a PHP function to handle method matching method_name.">
    <param type="resource" name="server" />
    <param type="string" name="method_name" />
    <param type="string" name="function" />
  </function>
  <function returnType="array" name="xmlrpc_parse_method_descriptions" description="Decodes XML into a list of method descriptions.">
    <param type="string" name="xml" />
  </function>
  <function returnType="mixed" name="xmlrpc_server_call_method" description="Parses XML requests and call methods.">
    <param type="resource" name="server" />
    <param type="string" name="xml" />
    <param type="mixed" name="user_data" />
    <param optional="true" type="array" name="output_options" />
  </function>
  <function returnType="int" name="xmlrpc_server_add_introspection_data" description="Adds introspection documentation.">
    <param type="resource" name="server" />
    <param type="array" name="desc" />
  </function>
  <function returnType="string" name="xmlrpc_get_type" description="Gets xmlrpc type for a PHP value. Especially useful for base64 and datetime strings.">
    <param type="mixed" name="value" />
  </function>
  <function returnType="bool" name="xmlrpc_set_type" description="Sets xmlrpc type, base64 or datetime, for a PHP string value.">
    <param type="string" name="value" />
    <param type="string" name="type" />
  </function>
  <function returnType="bool" name="xmlrpc_server_register_introspection_callback" description="Register a PHP function to generate documentation.">
    <param type="resource" name="server" />
    <param type="string" name="function" />
  </function>
  <function returnType="string" name="xmlrpc_encode_request" description="Generates XML for a method request.">
    <param type="string" name="method" />
    <param type="mixed" name="params" />
  </function>
  <function returnType="resource" castToFalse="true" name="xmlrpc_server_create" description="Creates an xmlrpc server." />
  <function returnType="void" name="xmlrpc_server_destroy" description="Destroys server resources.">
    <param type="resource" name="server" />
  </function>
  <function returnType="bool" name="xmlrpc_is_fault" description="Determines if an array value represents an XMLRPC fault.">
    <param type="array" name="arg" />
  </function>
</module>

=== d3sformal/weverca/External Sources/PhalangerOriginal/Deployment/TypeDefs/php_curl.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="string" name="curl_getinfo" description="Get information regarding a specific transfer.">
    <param type="resource" name="ch" />
    <param optional="true" type="int" name="opt" />
  </function>
  <function returnType="string" name="curl_error" description="Return a string contain the last error for the current session.">
    <param type="resource" name="ch" />
  </function>
  <function returnType="resource" castToFalse="true" name="curl_init" description="Initialize a CURL session.">
    <param optional="true" type="string" name="url" />
  </function>
  <function returnType="int" name="curl_errno" description="Return an integer containing the last error number.">
    <param type="resource" name="ch" />
  </function>
  <function returnType="string" name="curl_version" description="Return the CURL version string." />
  <function returnType="void" name="curl_close" description="Close a CURL session.">
    <param type="resource" name="ch" />
  </function>
  <function returnType="bool" name="curl_setopt" description="Set an option for a CURL transfer.">
    <param type="resource" name="ch" />
    <param type="string" name="option" />
    <param type="mixed" name="value" />
  </function>
  <function returnType="bool" name="curl_setopt" description="Set an option for a CURL transfer.">
    <param type="resource" name="ch" />
    <param type="int" name="option" />
    <param type="mixed" name="value" />
  </function>
  <function returnType="mixed" name="curl_exec" description="Perform a CURL session.">
    <param type="resource" name="ch" />
  </function>
  <function returnType="resource" name="curl_copy_handle" description="Copy a cURL handle along with all of its preferences.">
    <param type="resource" name="ch" />
  </function>
  <function returnType="int" name="curl_multi_add_handle" description="Add a normal cURL handle to a cURL multi handle.">
    <param type="resource" name="mh" />
    <param type="resource" name="ch" />
  </function>
  <function returnType="void" name="curl_multi_close" description="Close a set of cURL handles.">
    <param type="resource" name="mh" />
  </function>
  <function returnType="int" name="curl_multi_exec" description="Run the sub-connections of the current cURL handle.">
    <param type="resource" name="mh" />
    <param direction="inout" type="int" name="still_running" />
  </function>
  <function returnType="string" name="curl_multi_getcontent" description="Return the content of a cURL handle if CURLOPT_RETURNTRANSFER is set.">
    <param type="resource" name="ch" />
  </function>
  <function returnType="array" name="curl_multi_info_read" description="Get information about the current transfers.">
    <param type="resource" name="mh" />
  </function>
  <function returnType="resource" name="curl_multi_init" description="Returns a new cURL multi handle." />
  <function returnType="int" name="curl_multi_remove_handle" description="Remove a multi handle from a set of cURL handles.">
    <param type="resource" name="mh" />
    <param type="resource" name="ch" />
  </function>
  <function returnType="int" name="curl_multi_select" description="Get all the sockets associated with the cURL extension, which can then be &quot;selected=&quot;.">
    <param type="resource" name="mh" />
    <param optional="true" type="float" name="timeout" />
  </function>
</module>

=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/php_sybase_ct.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="int" name="sybase_affected_rows" description="Gets number of affected rows in last query.">
    <param optional="true" type="resource" name="link_identifier" />
  </function>
  <function returnType="bool" name="sybase_close" description="Closes a Sybase connection.">
    <param optional="true" type="resource" name="link_identifier" />
  </function>
  <function returnType="resource" castToFalse="true" name="sybase_connect" description="Opens a Sybase server connection.">
    <param optional="true" type="string" name="servername" />
    <param optional="true" type="string" name="username" />
    <param optional="true" type="string" name="password" />
    <param optional="true" type="string" name="charset" />
    <param optional="true" type="string" name="appname" />
  </function>
  <function returnType="bool" name="sybase_data_seek" description="Moves internal row pointer.">
    <param type="resource" name="result_identifier" />
    <param type="int" name="row_number" />
  </function>
  <function returnType="void" name="sybase_deadlock_retry_count" description="Sets the deadlock retry count.">
    <param type="int" name="retry_count" />
  </function>
  <function returnType="array" name="sybase_fetch_array" description="Fetch row as array.">
    <param type="resource" name="result" />
  </function>
  <function returnType="array" name="sybase_fetch_assoc" description="Fetch a result row as an associative array.">
    <param type="resource" name="result" />
  </function>
  <function returnType="object" name="sybase_fetch_field" description="Get field information from a result.">
    <param type="resource" name="result" />
    <param optional="true" type="int" name="field_offset" />
  </function>
  <function returnType="object" name="sybase_fetch_object" description="Fetch a row as an object.">
    <param type="resource" name="result" />
    <param optional="true" type="mixed" name="object" />
  </function>
  <function returnType="array" name="sybase_fetch_row" description="Get a result row as an enumerated array.">
    <param type="resource" name="result" />
  </function>
  <function returnType="bool" name="sybase_field_seek" description="Sets field offset.">
    <param type="resource" name="result" />
    <param type="int" name="field_offset" />
  </function>
  <function returnType="bool" name="sybase_free_result" description="Frees result memory.">
    <param type="resource" name="result" />
  </function>
  <function returnType="string" name="sybase_get_last_message" description="Returns the last message from the server." />
  <function returnType="void" name="sybase_min_client_severity" description="Sets minimum client severity.">
    <param type="int" name="severity" />
  </function>
  <function returnType="void" name="sybase_min_error_severity" description="Sets minimum error severity.">
    <param type="int" name="severity" />
  </function>
  <function returnType="void" name="sybase_min_message_severity" description="Sets minimum message severity.">
    <param type="int" name="severity" />
  </function>
  <function returnType="void" name="sybase_min_server_severity" description="Sets minimum server severity.">
    <param type="int" name="severity" />
  </function>
  <function returnType="int" name="sybase_num_fields" description="Gets the number of fields in a result set.">
    <param type="resource" name="result" />
  </function>
  <function returnType="int" name="sybase_num_rows" description="Get number of rows in a result set.">
    <param type="resource" name="result" />
  </function>
  <function returnType="resource" castToFalse="true" name="sybase_pconnect" description="Open persistent Sybase connection.">
    <param optional="true" type="string" name="servername" />
    <param optional="true" type="string" name="username" />
    <param optional="true" type="string" name="password" />
    <param optional="true" type="string" name="charset" />
    <param optional="true" type="string" name="appname" />
  </function>
  <function returnType="resource" castToFalse="true" name="sybase_query" description="Sends a Sybase query.">
    <param type="string" name="query" />
    <param type="resource" name="link_identifier" />
  </function>
  <function returnType="string" name="sybase_result" description="Get result data.">
    <param type="resource" name="result" />
    <param type="int" name="row" />
    <param type="mixed" name="field" />
  </function>
  <function returnType="bool" name="sybase_select_db" description="Selects a Sybase database.">
    <param type="string" name="database_name" />
    <param optional="true" type="resource" name="link_identifier" />
  </function>
  <function returnType="bool" name="sybase_set_message_handler" description="Sets the handler called when a server message is raised.">
    <param type="string" name="handler" />
    <param optional="true" type="resource" name="connection" />
  </function>
  <function returnType="resource" castToFalse="true" name="sybase_unbuffered_query" description="Send a Sybase query and do not block.">
    <param type="string" name="query" />
    <param type="resource" name="link_identifier" />
    <param optional="true" type="bool" name="store_result" />
  </function>
</module>

=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/php_db.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="int" name="dbmreplace" description="Replaces the value for a key in a dbm database.">
    <param type="int" name="dbm_identifier" />
    <param type="string" name="key" />
    <param type="string" name="value" />
  </function>
  <function returnType="bool" name="dbmclose" description="Closes a dbm database.">
    <param type="int" name="dbm_identifier" />
  </function>
  <function returnType="int" name="dbminsert" description="Inserts a value for a key in a dbm database.">
    <param type="int" name="dbm_identifier" />
    <param type="string" name="key" />
    <param type="string" name="value" />
  </function>
  <function returnType="int" name="dbmdelete" description="Deletes the value for a key from a dbm database.">
    <param type="int" name="dbm_identifier" />
    <param type="string" name="key" />
  </function>
  <function returnType="string" name="dbmfirstkey" description="Retrieves the first key from a dbm database.">
    <param type="int" name="dbm_identifier" />
  </function>
  <function returnType="string" name="dbmnextkey" description="Retrieves the next key from a dbm database.">
    <param type="int" name="dbm_identifier" />
    <param type="string" name="key" />
  </function>
  <function returnType="string" name="dbmfetch" description="Fetches a value for a key from a dbm database.">
    <param type="int" name="dbm_identifier" />
    <param type="string" name="key" />
  </function>
  <function returnType="int" name="dbmexists" description="Tells if a value exists for a key in a dbm database.">
    <param type="int" name="dbm_identifier" />
    <param type="string" name="key" />
  </function>
  <function returnType="string" name="dblist" description="Describes the dbm-compatible library being used." />
  <function returnType="int" name="dbmopen" description="Opens a dbm database.">
    <param type="string" name="filename" />
    <param type="string" name="mode" />
  </function>
</module>

=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/php_xml.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="string" name="utf8_decode" description="Converts a string with ISO-8859-1 characters encoded with UTF-8 to single-byte ISO-8859-1.">
    <param type="string" name="data" />
  </function>
  <function returnType="string" name="utf8_encode" description="encodes an ISO-8859-1 string to UTF-8.">
    <param type="string" name="data" />
  </function>
  <function returnType="string" name="xml_error_string" description="get XML parser error string.">
    <param type="int" name="code" />
  </function>
  <function returnType="int" name="xml_get_current_byte_index" description="get current byte index for an XML parser.">
    <param type="resource" name="parser" />
  </function>
  <function returnType="int" name="xml_get_current_column_number" description="Get current column number for an XML parser.">
    <param type="resource" name="parser" />
  </function>
  <function returnType="int" name="xml_get_current_line_number" description="get current line number for an XML parser.">
    <param type="resource" name="parser" />
  </function>
  <function returnType="int" name="xml_get_error_code" description="get XML parser error code.">
    <param type="resource" name="parser" />
  </function>
  <function returnType="int" name="xml_parse_into_struct" description="Parse XML data into an array structure.">
    <param type="resource" name="parser" />
    <param type="string" name="data" />
    <param direction="out" type="array" name="values" />
    <param direction="out" optional="true" type="array" name="index" />
  </function>
  <function returnType="bool" name="xml_parse" description="start parsing an XML document.">
    <param type="resource" name="parser" />
    <param type="string" name="data" />
    <param optional="true" type="bool" name="is_final" />
  </function>
  <function returnType="resource" castToFalse="true" name="xml_parser_create_ns" description="Create an XML parser with namespace support.">
    <param optional="true" type="string" name="encoding" />
    <param optional="true" type="string" name="separator" />
  </function>
  <function returnType="resource" castToFalse="true" name="xml_parser_create" description="create an XML parser.">
    <param optional="true" type="string" name="encoding" />
  </function>
  <function returnType="bool" name="xml_parser_free" description="Free an XML parser.">
    <param type="resource" name="parser" />
  </function>
  <function returnType="mixed" name="xml_parser_get_option" description="get options from an XML parser.">
    <param type="resource" name="parser" />
    <param type="int" name="option" />
  </function>
  <function returnType="bool" name="xml_parser_set_option" description="set options in an XML parser.">
    <param type="resource" name="parser" />
    <param type="int" name="option" />
    <param type="mixed" name="value" />
  </function>
  <function returnType="bool" name="xml_set_character_data_handler" description="set up character data handler.">
    <param type="resource" name="parser" />
    <param type="mixed" name="handler" />
  </function>
  <function returnType="bool" name="xml_set_default_handler" description="set up default handler.">
    <param type="resource" name="parser" />
    <param type="mixed" name="handler" />
  </function>
  <function returnType="bool" name="xml_set_element_handler" description="set up start and end element handlers.">
    <param type="resource" name="parser" />
    <param type="mixed" name="start_element_handler" />
    <param type="mixed" name="end_element_handler" />
  </function>
  <function returnType="bool" name="xml_set_end_namespace_decl_handler" description="Set up character data handler.">
    <param type="resource" name="pind" />
    <param type="mixed" name="handler" />
  </function>
  <function returnType="bool" name="xml_set_external_entity_ref_handler" description="set up external entity reference handler.">
    <param type="resource" name="parser" />
    <param type="mixed" name="handler" />
  </function>
  <function returnType="bool" name="xml_set_notation_decl_handler" description="set up notation declaration handler.">
    <param type="resource" name="parser" />
    <param type="mixed" name="handler" />
  </function>
  <function returnType="void" name="xml_set_object" description="Use XML Parser within an object.">
    <param type="resource" name="parser" />
    <param direction="inout" bind="true" type="object" name="object" />
  </function>
  <function returnType="bool" name="xml_set_processing_instruction_handler" description="Set up processing instruction (PI) handler.">
    <param type="resource" name="parser" />
    <param type="mixed" name="handler" />
  </function>
  <function returnType="bool" name="xml_set_start_namespace_decl_handler" description="Set up character data handler.">
    <param type="resource" name="pind" />
    <param type="mixed" name="hdl" />
  </function>
  <function returnType="bool" name="xml_set_unparsed_entity_decl_handler" description="Set up unparsed entity declaration handler.">
    <param type="resource" name="parser" />
    <param type="mixed" name="handler" />
  </function>
</module>
