=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/module.dtd
<!ENTITY % phpType "bool | int | float | string | array | resource | object | mixed">

<!ELEMENT module (class | function)*>
<!ELEMENT class (function*)>
<!ELEMENT function (param*, alias*)>
<!ELEMENT alias EMPTY>
<!ELEMENT param EMPTY>

<!ATTLIST module
			earlyInit (false | true) "false">
<!ATTLIST class
			name CDATA #REQUIRED
			arrayGetter CDATA #IMPLIED
			arraySetter CDATA #IMPLIED
      description CDATA #IMPLIED>
<!ATTLIST function
			name CDATA #REQUIRED
			returnType (%phpType; | void) "mixed"
			static (false | true) "false"
			castToFalse (false | true) "false"
			marshalBoundVars (none | in | out | inout) "none"
			description CDATA #IMPLIED>
<!ATTLIST alias
      name CDATA #REQUIRED>
<!ATTLIST param
			name CDATA #IMPLIED
			type (%phpType;) "mixed"
			bind (false | true) "false"
			direction (in | out | inout) "in"
			optional (false | true | vararg) "false">

=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/php_fileinfo.php5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="string" name="finfo_buffer" description="This function is used to get information about binary data in a string.">
    <param type="resource" name="finfo" />
    <param type="string" name="string" optional="true" />
    <param type="int" name="options" optional="true" />
    <param type="resource" name="context" optional="true" />
  </function>
  <function returnType="bool" name="finfo_close" description="This function closes the resource opened by finfo_open().">
    <param type="resource" name="finfo" />
  </function>
  <function returnType="string" name="finfo_file" description="This function is used to get information about a file.">
    <param type="resource" name="finfo" />
    <param type="string" name="file_name" />
    <param type="int" name="options" optional="true" />
    <param type="resource" name="context" optional="true" />
  </function>
  <function returnType="resource" name="finfo_open" description="This function opens a magic database and returns its resource.">
    <param type="int" name="options" optional="true" />
    <param type="string" name="magic_file" optional="true" />
  </function>
  <function returnType="bool" name="finfo_set_flags" description="This function sets various Fileinfo options. Options can be set also directly in finfo_open() or other Fileinfo functions.">
    <param type="resource" name="finfo" />
    <param type="int" name="options" />
  </function>
  <function returnType="string" name="mime_content_type" description="Returns the MIME content type for a file as determined by using information from the magic.mime file.">
    <param type="string" name="filename" />
  </function>
  <class name="finfo" description="Finfo class, which exports methods which resemble finfo functions." >
    <function returnType="string" name="buffer" description="This function is used to get information about binary data in a string.">
        <param type="string" name="string" optional="true" />
        <param type="int" name="options" optional="true" />
        <param type="resource" name="context" optional="true" />
      </function>
    <function returnType="string" name="file" description="This function is used to get information about a file.">
      <param type="string" name="file_name" />
      <param type="int" name="options" optional="true" />
      <param type="resource" name="context" optional="true" />
    </function>
    <function returnType="bool" name="set_flags" description="This function sets various Fileinfo options. Options can be set also directly in finfo_open() or other Fileinfo functions.">
      <param type="int" name="options" />
    </function>
  </class>
</module>

=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/php_java.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="void" name="java_last_exception_clear" description="Clear last Java exception." />
  <function returnType="object" name="java_last_exception_get" description="Get last Java exception." />
  
  <class name="Java">
    <function name="Java" description="Constructor.">
      <param type="string" name="java_class_name" />
      <param type="array" name="args" />
    </function>
    <function returnType="mixed" name="__call" description="Calls a Java method.">
      <param type="string" name="java_method_name" />
      <param type="array" name="args" />
    </function>
    <function returnType="mixed" name="__get" description="Reads a Java property.">
      <param type="string" name="java_property_name" />
    </function>
    <function returnType="void" name="__set" description="Writes a Java property.">
      <param type="string" name="java_property_name" />
      <param type="mixed" name="value" />
    </function>
  </class>
</module>

=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/php_mssql.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="bool" name="mssql_bind" description="Adds a parameter to a stored procedure or a remote stored procedure.">
    <param type="resource" name="stmt" />
    <param type="string" name="param_name" />
    <param bind="true" direction="inout" type="mixed" name="var" />
    <param type="int" name="type" />
    <param optional="true" type="bool" name="is_output" />
    <param optional="true" type="bool" name="is_null" />
    <param optional="true" type="int" name="maxlen" />
  </function>
  <function returnType="bool" name="mssql_close" description="Close MS SQL Server connection.">
    <param optional="true" type="resource" name="link_identifier" />
  </function>
  <function returnType="resource" castToFalse="true" name="mssql_connect" description="Open MS SQL server connection.">
    <param optional="true" type="string" name="servername" />
    <param optional="true" type="string" name="username" />
    <param optional="true" type="string" name="password" />
  </function>
  <function returnType="bool" name="mssql_data_seek" description="Moves internal row pointer.">
    <param type="resource" name="result_identifier" />
    <param type="int" name="row_number" />
  </function>
  <function marshalBoundVars="out" returnType="mixed" name="mssql_execute" description="Executes a stored procedure on a MS SQL server database.">
    <param type="resource" name="stmt" />
    <param optional="true" type="bool" name="skip_results" />
  </function>
  <function returnType="array" castToFalse="true" name="mssql_fetch_array" description="Fetch a result row as an associative array, a numeric array, or both.">
    <param type="resource" name="result" />
    <param optional="true" type="int" name="result_type" />
  </function>
  <function returnType="array" name="mssql_fetch_assoc" description="Returns an associative array of the current row in the result set specified by result_id.">
    <param type="resource" name="result_id" />
  </function>
  <function returnType="int" name="mssql_fetch_batch" description="Returns the next batch of records.">
    <param type="resource" name="result_index" />
  </function>
  <function returnType="object" name="mssql_fetch_field" description="Get field information.">
    <param type="resource" name="result" />
    <param optional="true" type="int" name="field_offset" />
  </function>
  <function returnType="object" name="mssql_fetch_object" description="Fetch row as object.">
    <param type="resource" name="result" />
  </function>
  <function returnType="array" name="mssql_fetch_row" description="Get row as enumerated array.">
    <param type="resource" name="result" />
  </function>
  <function returnType="int" name="mssql_field_length" description="Get the length of a field.">
    <param type="resource" name="result" />
    <param optional="true" type="int" name="offset" />
  </function>
  <function returnType="string" name="mssql_field_name" description="Get the name of a field.">
    <param type="resource" name="result" />
    <param optional="true" type="int" name="offset" />
  </function>
  <function returnType="bool" name="mssql_field_seek" description="Seeks to the specified field offset.">
    <param type="resource" name="result" />
    <param type="int" name="field_offset" />
  </function>
  <function returnType="string" name="mssql_field_type" description="Gets the type of a field.">
    <param type="resource" name="result" />
    <param optional="true" type="int" name="offset" />
  </function>
  <function returnType="bool" name="mssql_free_result" description="Free result memory.">
    <param type="resource" name="result" />
  </function>
  <function returnType="bool" name="mssql_free_statement" description="Free statement memory.">
    <param type="resource" name="statement" />
  </function>
  <function returnType="string" name="mssql_get_last_message" description="Returns the last message from the server." />
  <function returnType="string" name="mssql_guid_string" description="Converts a 16 byte binary GUID to a string.">
    <param type="string" name="binary" />
    <param optional="true" type="int" name="short_format" />
  </function>
  <function returnType="resource" castToFalse="true" name="mssql_init" description="Initializes a stored procedure or a remote stored procedure.">
    <param type="string" name="sp_name" />
    <param optional="true" type="resource" name="conn_id" />
  </function>
  <function returnType="void" name="mssql_min_error_severity" description="Sets the lower error severity.">
    <param type="int" name="severity" />
  </function>
  <function returnType="void" name="mssql_min_message_severity" description="Sets the lower message severity.">
    <param type="int" name="severity" />
  </function>
  <function returnType="bool" name="mssql_next_result" description="Move the internal result pointer to the next result.">
    <param type="resource" name="result_id" />
  </function>
  <function returnType="int" name="mssql_num_fields" description="Gets the number of fields in result.">
    <param type="resource" name="result" />
  </function>
  <function returnType="int" name="mssql_num_rows" description="Gets the number of rows in result.">
    <param type="resource" name="result" />
  </function>
  <function returnType="resource" castToFalse="true" name="mssql_pconnect" description="Open persistent MS SQL connection.">
    <param optional="true" type="string" name="servername" />
    <param optional="true" type="string" name="username" />
    <param optional="true" type="string" name="password" />
  </function>
  <function returnType="mixed" castToFalse="false" name="mssql_query" description="Send MS SQL query.">
    <param type="string" name="query" />
    <param optional="true" type="resource" name="link_identifier" />
    <param optional="true" type="int" name="batch_size" />
  </function>
  <function returnType="string" name="mssql_result" description="Get result data.">
    <param type="resource" name="result" />
    <param type="int" name="row" />
    <param type="mixed" name="field" />
  </function>
  <function returnType="int" name="mssql_rows_affected" description="Returns the number of records affected by the query.">
    <param type="resource" name="conn_id" />
  </function>
  <function returnType="bool" name="mssql_select_db" description="Select MS SQL database.">
    <param type="string" name="database_name" />
    <param optional="true" type="resource" name="link_identifier" />
  </function>
</module>

=== d3sformal/weverca/External Sources/PhalangerOriginal/Deployment/TypeDefs/php_yaz.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="string" name="yaz_addinfo" description="Returns additional error information.">
    <param type="resource" name="id" />
  </function>
  <function returnType="int" name="yaz_ccl_conf" description="Configure CCL parser.">
    <param type="resource" name="id" />
    <param type="array" name="config" />
  </function>
  <function returnType="bool" name="yaz_ccl_parse" description="Invoke CCL Parser.">
    <param type="resource" name="id" />
    <param type="string" name="query" />
    <param direction="out" type="array" name="result" />
  </function>
  <function returnType="bool" name="yaz_close" description="Close YAZ connection.">
    <param type="resource" name="id" />
  </function>
  <function returnType="resource" castToFalse="true" name="yaz_connect" description="Prepares for a connection to a Z39.50 server.">
    <param type="string" name="zurl" />
    <param optional="true" type="mixed" name="options" />
  </function>
  <function returnType="bool" name="yaz_database" description="Specifies the databases within a session.">
    <param type="resource" name="id" />
    <param type="string" name="databases" />
  </function>
  <function returnType="bool" name="yaz_element" description="Specifies Element-Set Name for retrieval.">
    <param type="resource" name="id" />
    <param type="string" name="elementset" />
  </function>
  <function returnType="int" name="yaz_errno" description="Returns error number.">
    <param type="resource" name="id" />
  </function>
  <function returnType="string" name="yaz_error" description="Returns error description.">
    <param type="resource" name="id" />
  </function>
  <function returnType="array" name="yaz_es_result" description="Inspects Extended Services Result.">
    <param type="resource" name="id" />
  </function>
  <function returnType="string" name="yaz_get_option" description="Returns value of option for connection.">
    <param type="resource" name="id" />
    <param type="string" name="name" />
  </function>
  <function returnType="int" name="yaz_hits" description="Returns number of hits for last search.">
    <param type="resource" name="id" />
  </function>
  <function returnType="int" name="yaz_itemorder" description="Prepares for Z39.50 Item Order with an ILL-Request package.">
    <param type="resource" name="id" />
    <param type="array" name="args" />
  </function>
  <function returnType="bool" name="yaz_present" description="Prepares for retrieval (Z39.50 present).">
    <param type="resource" name="id" />
  </function>
  <function returnType="bool" name="yaz_range" description="Specifies the maximum number of records to retrieve.">
    <param type="resource" name="id" />
    <param type="int" name="start" />
    <param type="int" name="number" />
  </function>
  <function returnType="string" name="yaz_record" description="Returns a record.">
    <param type="resource" name="id" />
    <param type="int" name="pos" />
    <param type="string" name="type" />
  </function>
  <function returnType="array" name="yaz_scan_result" description="Returns Scan Response result.">
    <param type="resource" name="id" />
    <param direction="out" optional="true" type="array" name="result" />
  </function>
  <function returnType="int" name="yaz_scan" description="Prepares for a scan.">
    <param type="resource" name="id" />
    <param type="string" name="type" />
    <param type="string" name="startterm" />
    <param optional="true" type="array" name="flags" />
  </function>
  <function returnType="int" name="yaz_schema" description="Specifies schema for retrieval.">
    <param type="resource" name="id" />
    <param type="string" name="schema" />
  </function>
  <function returnType="int" name="yaz_search" description="Prepares for a search.">
    <param type="resource" name="id" />
    <param type="string" name="type" />
    <param type="string" name="query" />
  </function>
  <function returnType="string" name="yaz_set_option" description="Sets one or more options for connection.">
    <param type="resource" name="id" />
    <param type="string" name="name" />
    <param type="string" name="value" />
  </function>
  <function returnType="int" name="yaz_sort" description="Sets sorting criteria.">
    <param type="resource" name="id" />
    <param type="string" name="criteria" />
  </function>
  <function returnType="int" name="yaz_syntax" description="Specifies the preferred record syntax for retrieval.">
    <param type="resource" name="id" />
    <param type="string" name="syntax" />
  </function>
  <function returnType="int" name="yaz_wait" description="Wait for Z39.50 requests to complete.">
    <param optional="true" type="array" name="options" />
  </function>
</module>

=== d3sformal/weverca/External Sources/PhalangerOriginal/Deployment/TypeDefs/php_calendar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="int" name="cal_days_in_month" description="Return the number of days in a month for a given year and calendar.">
    <param type="int" name="calendar" />
    <param type="int" name="month" />
    <param type="int" name="year" />
  </function>
  <function returnType="array" name="cal_from_jd" description="Converts from Julian Day Count to a supported calendar.">
    <param type="int" name="jd" />
    <param type="int" name="calendar" />
  </function>
  <function returnType="array" name="cal_info" description="Returns information about a particular calendar.">
    <param optional="true" type="int" name="calendar" />
  </function>
  <function returnType="int" name="cal_to_jd" description="Converts from a supported calendar to Julian Day Count.">
    <param type="int" name="calendar" />
    <param type="int" name="month" />
    <param type="int" name="day" />
    <param type="int" name="year" />
  </function>
  <function returnType="int" name="easter_date" description="Get Unix timestamp for midnight on Easter of a given year.">
    <param optional="true" type="int" name="year" />
  </function>
  <function returnType="int" name="easter_days" description="Get number of days after March 21 on which Easter falls for a given year.">
    <param optional="true" type="int" name="year" />
    <param optional="true" type="int" name="method" />
  </function>
  <function returnType="int" name="FrenchToJD" description="Converts a date from the French Republican Calendar to a Julian Day Count.">
    <param type="int" name="month" />
    <param type="int" name="day" />
    <param type="int" name="year" />
  </function>
  <function returnType="int" name="GregorianToJD" description="Converts a Gregorian date to Julian Day Count.">
    <param type="int" name="month" />
    <param type="int" name="day" />
    <param type="int" name="year" />
  </function>
  <function returnType="mixed" name="JDDayOfWeek" description="Returns the day of the week.">
    <param type="int" name="julianday" />
    <param optional="true" type="int" name="mode" />
  </function>
  <function returnType="string" name="JDMonthName" description="Returns a month name.">
    <param type="int" name="julianday" />
    <param type="int" name="mode" />
  </function>
  <function returnType="string" name="JDToFrench" description="Converts a Julian Day Count to the French Republican Calendar.">
    <param type="int" name="juliandaycount" />
  </function>
  <function returnType="string" name="JDToGregorian" description="Converts Julian Day Count to Gregorian date.">
    <param type="int" name="julianday" />
  </function>
  <function returnType="string" name="jdtojewish" description="Converts a Julian day count to a Jewish calendar date.">
    <param type="int" name="juliandaycount" />
    <param optional="true" type="bool" name="hebrew" />
    <param optional="true" type="int" name="fl" />
  </function>
  <function returnType="string" name="JDToJulian" description="Converts a Julian Day Count to a Julian Calendar Date.">
    <param type="int" name="julianday" />
  </function>
  <function returnType="int" name="jdtounix" description="Convert Julian Day to Unix timestamp.">
    <param type="int" name="jday" />
  </function>
  <function returnType="int" name="JewishToJD" description="Converts a date in the Jewish Calendar to Julian Day Count.">
    <param type="int" name="month" />
    <param type="int" name="day" />
    <param type="int" name="year" />
  </function>
  <function returnType="int" name="JulianToJD" description="Converts a Julian Calendar date to Julian Day Count.">
    <param type="int" name="month" />
    <param type="int" name="day" />
    <param type="int" name="year" />
  </function>
  <function returnType="int" name="unixtojd" description="Convert Unix timestamp to Julian Day.">
    <param optional="true" type="int" name="timestamp" />
  </function>
</module>

=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/php_ifx.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="int" name="ifx_affected_rows" description="Get number of rows affected by a query.">
    <param type="resource" name="result_id" />
  </function>
  <function returnType="void" name="ifx_blobinfile_mode" description="Set the default blob mode for all select queries.">
    <param type="int" name="mode" />
  </function>
  <function returnType="void" name="ifx_byteasvarchar" description="Set the default byte mode.">
    <param type="int" name="mode" />
  </function>
  <function returnType="bool" name="ifx_close" description="Close Informix connection.">
    <param optional="true" type="resource" name="link_identifier" />
  </function>
  <function returnType="resource" castToFalse="true" name="ifx_connect" description="Open Informix server connection.">
    <param optional="true" type="string" name="database" />
    <param optional="true" type="string" name="userid" />
    <param optional="true" type="string" name="password" />
  </function>
  <function returnType="int" name="ifx_copy_blob" description="Duplicates the given blob object.">
    <param type="int" name="bid" />
  </function>
  <function returnType="int" name="ifx_create_blob" description="Creates an blob object.">
    <param type="int" name="type" />
    <param type="int" name="mode" />
    <param type="string" name="param" />
  </function>
  <function returnType="int" name="ifx_create_char" description="Creates an char object.">
    <param type="string" name="param" />
  </function>
  <function returnType="bool" name="ifx_do" description="Execute a previously prepared SQL-statement.">
    <param type="resource" name="result_id" />
  </function>
  <function returnType="string" name="ifx_error" description="Returns error code of last Informix call." />
  <function returnType="string" name="ifx_errormsg" description="Returns error message of last Informix call.">
    <param optional="true" type="int" name="errorcode" />
  </function>
  <function returnType="array" name="ifx_fetch_row" description="Get row as enumerated array.">
    <param type="resource" name="result_id" />
    <param optional="true" type="mixed" name="position" />
  </function>
  <function returnType="array" name="ifx_fieldproperties" description="List of SQL fieldproperties.">
    <param type="resource" name="result_id" />
  </function>
  <function returnType="array" name="ifx_fieldtypes" description="List of Informix SQL fields.">
    <param type="resource" name="result_id" />
  </function>
  <function returnType="bool" name="ifx_free_blob" description="Deletes the blob object.">
    <param type="int" name="bid" />
  </function>
  <function returnType="bool" name="ifx_free_char" description="Deletes the char object.">
    <param type="int" name="bid" />
  </function>
  <function returnType="bool" name="ifx_free_result" description="Releases resources for the query.">
    <param type="resource" name="result_id" />
  </function>
  <function returnType="string" name="ifx_get_blob" description="Return the content of a blob object.">
    <param type="int" name="bid" />
  </function>
  <function returnType="string" name="ifx_get_char" description="Return the content of the char object.">
    <param type="int" name="bid" />
  </function>
  <function returnType="array" name="ifx_getsqlca" description="Get the contents of sqlca.sqlerrd[0..5] after a query.">
    <param type="resource" name="result_id" />
  </function>
  <function returnType="int" name="ifx_htmltbl_result" description="Formats all rows of a query into a HTML table.">
    <param type="resource" name="result_id" />
    <param optional="true" type="string" name="html_table_options" />
  </function>
  <function returnType="void" name="ifx_nullformat" description="Sets the default return value on a fetch row.">
    <param type="int" name="mode" />
  </function>
  <function returnType="int" name="ifx_num_fields" description="Returns the number of columns in the query.">
    <param type="resource" name="result_id" />
  </function>
  <function returnType="int" name="ifx_num_rows" description="Count the rows already fetched from a query.">
    <param type="resource" name="result_id" />
  </function>
  <function returnType="resource" castToFalse="true" name="ifx_pconnect" description="Open persistent Informix connection.">
    <param optional="true" type="string" name="database" />
    <param optional="true" type="string" name="userid" />
    <param optional="true" type="string" name="password" />
  </function>
  <function returnType="resource" castToFalse="true" name="ifx_prepare" description="Prepare an SQL-statement for execution.">
    <param type="string" name="query" />
    <param type="resource" name="conn_id" />
    <param optional="true" type="int" name="cursor_def" />
    <param optional="true" type="mixed" name="blobidarray" />
  </function>
  <function returnType="resource" castToFalse="true" name="ifx_query" description="Send Informix query.">
    <param type="string" name="query" />
    <param type="resource" name="link_identifier" />
    <param optional="true" type="int" name="cursor_type" />
    <param optional="true" type="mixed" name="blobidarray" />
  </function>
  <function returnType="void" name="ifx_textasvarchar" description="Set the default text mode.">
    <param type="int" name="mode" />
  </function>
  <function returnType="bool" name="ifx_update_blob" description="Updates the content of the blob object.">
    <param type="int" name="bid" />
    <param type="string" name="content" />
  </function>
  <function returnType="bool" name="ifx_update_char" description="Updates the content of the char object.">
    <param type="int" name="bid" />
    <param type="string" name="content" />
  </function>
  <function returnType="bool" name="ifxus_close_slob" description="Deletes the slob object.">
    <param type="int" name="bid" />
  </function>
  <function returnType="int" name="ifxus_create_slob" description="Creates an slob object and opens it.">
    <param type="int" name="mode" />
  </function>
  <function returnType="bool" name="ifxus_free_slob" description="Deletes the slob object.">
    <param type="int" name="bid" />
  </function>
  <function returnType="int" name="ifxus_open_slob" description="Opens an slob object.">
    <param type="int" name="bid" />
    <param type="int" name="mode" />
  </function>
  <function returnType="string" name="ifxus_read_slob" description="Reads nbytes of the slob object.">
    <param type="int" name="bid" />
    <param type="int" name="nbytes" />
  </function>
  <function returnType="int" name="ifxus_seek_slob" description="Sets the current file or seek position.">
    <param type="int" name="bid" />
    <param type="int" name="mode" />
    <param type="int" name="offset" />
  </function>
  <function returnType="int" name="ifxus_tell_slob" description="Returns the current file or seek position.">
    <param type="int" name="bid" />
  </function>
  <function returnType="int" name="ifxus_write_slob" description="Writes a string into the slob object.">
    <param type="int" name="bid" />
    <param type="string" name="content" />
  </function>
</module>
