=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/module.dtd
<!ENTITY % phpType "bool | int | float | string | array | resource | object | mixed">

<!ELEMENT module (class | function)*>
<!ELEMENT class (function*)>
<!ELEMENT function (param*, alias*)>
<!ELEMENT alias EMPTY>
<!ELEMENT param EMPTY>

<!ATTLIST module
			earlyInit (false | true) "false">
<!ATTLIST class
			name CDATA #REQUIRED
			arrayGetter CDATA #IMPLIED
			arraySetter CDATA #IMPLIED
      description CDATA #IMPLIED>
<!ATTLIST function
			name CDATA #REQUIRED
			returnType (%phpType; | void) "mixed"
			static (false | true) "false"
			castToFalse (false | true) "false"
			marshalBoundVars (none | in | out | inout) "none"
			description CDATA #IMPLIED>
<!ATTLIST alias
      name CDATA #REQUIRED>
<!ATTLIST param
			name CDATA #IMPLIED
			type (%phpType;) "mixed"
			bind (false | true) "false"
			direction (in | out | inout) "in"
			optional (false | true | vararg) "false">

=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/php_hash.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="array" name="hash_algos" description="Return a list of registered hashing algorithms." />
  <function returnType="string" name="hash_file" description="Generate a hash value using the contents of a given file.">
    <param type="string" name="algo" />
    <param type="string" name="filename" />
    <param optional="true" type="bool" name="raw_output" />
  </function>
  <function returnType="string" name="hash_final" description="Finalize an incremental hash and return resulting digest.">
    <param type="resource" name="context" />
    <param optional="true" type="bool" name="raw_output" />
  </function>
  <function returnType="string" name="hash_hmac_file" description="Generate a keyed hash value using the HMAC method and the contents of a given file.">
    <param type="string" name="algo" />
    <param type="string" name="filename" />
    <param type="string" name="key" />
    <param optional="true" type="bool" name="raw_output" />
  </function>
  <function returnType="string" name="hash_hmac" description="Generate a keyed hash value using the HMAC method.">
    <param type="string" name="algo" />
    <param type="string" name="data" />
    <param type="string" name="key" />
    <param optional="true" type="bool" name="raw_output" />
  </function>
  <function returnType="resource" name="hash_init" description="Initialize an incremental hashing context.">
    <param type="string" name="algo" />
    <param optional="true" type="int" name="options" />
    <param optional="true" type="string" name="key" />
  </function>
  <function returnType="bool" name="hash_update_file" description="Pump data into an active hashing context from a file.">
    <param type="resource" name="context" />
    <param type="string" name="filename" />
    <param optional="true" type="resource" name="context" />
  </function>
  <function returnType="int" name="hash_update_stream" description="Pump data into an active hashing context from an open stream.">
    <param type="resource" name="context" />
    <param type="resource" name="handle" />
    <param optional="true" type="int" name="length" />
  </function>
  <function returnType="bool" name="hash_update" description="Pump data into an active hashing context.">
    <param type="resource" name="context" />
    <param type="string" name="data" />
  </function>
  <function returnType="string" name="hash" description="Generate a hash value (message digest).">
    <param type="string" name="algo" />
    <param type="string" name="data" />
    <param optional="true" type="bool" name="raw_output" />
  </function>
</module>

=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/php_tidy.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="int" name="tidy_access_count" description="Returns the Number of Tidy accessibility warnings encountered for specified document.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="bool" name="tidy_clean_repair" description="Execute configured cleanup and repair operations on parsed markup.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="int" name="tidy_config_count" description="Returns the Number of Tidy configuration errors encountered for specified document.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="bool" name="tidy_diagnose" description="Run configured diagnostics on parsed and repaired markup.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="int" name="tidy_error_count" description="Returns the Number of Tidy errors encountered for specified document.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="object" name="tidy_get_body" description="Returns a tidyNode Object starting from the body tag of the tidy parse tree.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="array" name="tidy_get_config" description="Get current Tidy configuration.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="string" name="tidy_get_error_buffer" description="Return warnings and errors which occurred parsing the specified document.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="object" name="tidy_get_head" description="Returns a tidyNode Object starting from the head tag of the tidy parse tree.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="object" name="tidy_get_html" description="Returns a tidyNode Object starting from the html tag of the tidy parse tree.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="int" name="tidy_get_html_ver" description="Get the Detected HTML version for the specified document.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="mixed" name="tidy_getopt" description="Returns the value of the specified configuration option for the tidy document.">
    <param type="object" name="tidy" />
    <param type="string" name="option" />
  </function>
  <function returnType="string" name="tidy_get_opt_doc" description="Returns the documentation for the given option name.">
    <param type="object" name="tidy" />
    <param type="string" name="optname" />
  </function>
  <function returnType="string" name="tidy_get_output" description="Return a string representing the parsed tidy markup.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="string" name="tidy_get_release" description="Get release date (version) for Tidy library." />
  <function returnType="object" name="tidy_get_root" description="Returns a tidyNode object representing the root of the tidy parse tree.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="int" name="tidy_get_status" description="Get status of specified document.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="bool" name="tidy_is_xhtml" description="Indicates if the document is a XHTML document.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="bool" name="tidy_is_xml" description="Indicates if the document is a generic (non HTML/XHTML) XML document.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="void" name="tidy_load_config" description="Load an ASCII Tidy configuration file with the specified encoding.">
    <param type="string" name="filename" />
    <param type="string" name="encoding" />
  </function>
  <function returnType="object" castToFalse="true" name="tidy_parse_file" description="Parse markup in file or URI.">
    <param type="string" name="filename" />
    <param optional="true" type="mixed" name="config" />
    <param optional="true" type="string" name="encoding" />
    <param optional="true" type="bool" name="use_include_path" />
  </function>
  <function returnType="object" castToFalse="true" name="tidy_parse_string" description="Parse a document stored in a string.">
    <param type="string" name="input" />
    <param optional="true" type="mixed" name="config" />
    <param optional="true" type="string" name="encoding" />
  </function>
  <function returnType="string" name="tidy_repair_file" description="Repair a file and return it as a string.">
    <param type="string" name="filename" />
    <param optional="true" type="mixed" name="config" />
    <param optional="true" type="string" name="encoding" />
    <param optional="true" type="bool" name="use_include_path" />
  </function>
  <function returnType="string" name="tidy_repair_string" description="Repair a string using an optionally provided configuration file.">
    <param type="string" name="data" />
    <param optional="true" type="mixed" name="config" />
    <param optional="true" type="string" name="encoding" />
  </function>
  <function returnType="bool" name="tidy_reset_config" description="Restore Tidy configuration to default values." />
  <function returnType="bool" name="tidy_save_config" description="Save current settings to named file.">
    <param type="string" name="filename" />
  </function>
  <function returnType="bool" name="tidy_set_encoding" description="Set the input/output character encoding for parsing markup.">
    <param type="string" name="encoding" />
  </function>
  <function returnType="bool" name="tidy_setopt" description="Updates the configuration settings for the specified tidy document.">
    <param type="string" name="option" />
    <param type="mixed" name="value" />
  </function>
  <function returnType="int" name="tidy_warning_count" description="Returns the Number of Tidy warnings encountered for specified document.">
    <param type="object" name="tidy" />
  </function>
  <function returnType="string" name="ob_tidyhandler" description="ob_start callback function to repair the buffer.">
    <param type="string" name="input" />
    <param optional="true" type="int" name="mode" />
  </function>
</module>

=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/php_filepro.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="int" name="filepro_fieldcount" description="Find out how many fields are in a filePro database." />
  <function returnType="int" name="filepro_fieldwidth" description="Gets the width of a field.">
    <param type="int" name="field_number" />
  </function>
  <function returnType="int" name="filepro_rowcount" description="Find out how many rows are in a filePro database." />
  <function returnType="string" name="filepro_fieldname" description="Gets the name of a field.">
    <param type="int" name="fieldnumber" />
  </function>
  <function returnType="bool" name="filepro" description="Read and verify the map file.">
    <param type="string" name="directory" />
  </function>
  <function returnType="string" name="filepro_retrieve" description="Retrieves data from a filePro database.">
    <param type="int" name="row_number" />
    <param type="int" name="field_number" />
  </function>
  <function returnType="string" name="filepro_fieldtype" description="Gets the type of a field.">
    <param type="int" name="field_number" />
  </function>
</module>

=== d3sformal/weverca/External Sources/PhalangerOriginal/Deployment/TypeDefs/php_zlib.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="int" name="gzclose" description="Close an open gz-file pointer.">
    <param type="resource" name="zp" />
  </function>
  <function returnType="string" name="gzcompress" description="Compress a string.">
    <param type="string" name="data" />
    <param optional="true" type="int" name="level" />
  </function>
  <function returnType="string" name="gzdeflate" description="Deflate a string.">
    <param type="string" name="data" />
    <param optional="true" type="int" name="level" />
  </function>
  <function returnType="string" name="gzencode" description="Create a gzip compressed string.">
    <param type="string" name="data" />
    <param optional="true" type="int" name="level" />
    <param optional="true" type="int" name="encoding_mode" />
  </function>
  <function returnType="int" name="gzeof" description="Test for end-of-file on a gz-file pointer.">
    <param type="resource" name="zp" />
  </function>
  <function returnType="array" name="gzfile" description="Read entire gz-file into an array.">
    <param type="string" name="filename" />
    <param optional="true" type="int" name="use_include_path" />
  </function>
  <function returnType="string" name="gzgetc" description="Get character from gz-file pointer.">
    <param type="resource" name="zp" />
  </function>
  <function returnType="string" name="gzgets" description="Get line from file pointer.">
    <param type="resource" name="zp" />
    <param type="int" name="length" />
  </function>
  <function returnType="string" name="gzgetss" description="Get line from gz-file pointer and strip HTML tags.">
    <param type="resource" name="zp" />
    <param type="int" name="length" />
    <param optional="true" type="string" name="allowable_tags" />
  </function>
  <function returnType="string" name="gzinflate" description="Inflate a deflated string.">
    <param type="string" name="data" />
    <param optional="true" type="int" name="length" />
  </function>
  <function returnType="resource" castToFalse="true" name="gzopen" description="Open gz-file.">
    <param type="string" name="filename" />
    <param type="string" name="mode" />
    <param optional="true" type="int" name="use_include_path" />
  </function>
  <function returnType="int" name="gzpassthru" description="Output all remaining data on a gz-file pointer.">
    <param type="resource" name="zp" />
  </function>
  <function returnType="int" name="gzputs" description="Binary-safe gz-file write.">
    <param type="resource" name="zp" />
    <param type="string" name="string" />
    <param optional="true" type="int" name="length" />
  </function>
  <function returnType="string" name="gzread" description="Binary-safe gz-file read.">
    <param type="resource" name="zp" />
    <param type="int" name="length" />
  </function>
  <function returnType="int" name="gzrewind" description="Rewind the position of a gz-file pointer.">
    <param type="resource" name="zp" />
  </function>
  <function returnType="int" name="gzseek" description="Seek on a gz-file pointer.">
    <param type="resource" name="zp" />
    <param type="int" name="offset" />
  </function>
  <function returnType="int" name="gztell" description="Tell gz-file pointer read/write position.">
    <param type="resource" name="zp" />
  </function>
  <function returnType="string" name="gzuncompress" description="Uncompress a deflated string.">
    <param type="string" name="data" />
    <param optional="true" type="int" name="length" />
  </function>
  <function returnType="int" name="gzwrite" description="Binary-safe gz-file write.">
    <param type="resource" name="zp" />
    <param type="string" name="string" />
    <param optional="true" type="int" name="length" />
  </function>
  <function returnType="int" name="readgzfile" description="Output a gz-file.">
    <param type="string" name="filename" />
    <param optional="true" type="int" name="use_include_path" />
  </function>
  <function returnType="string" name="zlib_get_coding_type" description="Returns the coding type used for output compression." />
</module>

=== d3sformal/weverca/External Sources/PhalangerOriginal/Deployment/TypeDefs/php_zip.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="string" name="zip_entry_compressionmethod" description="Return a string containing the compression method used on a particular entry.">
    <param type="resource" name="zip_entry" />
  </function>
  <function returnType="string" name="zip_entry_name" description="Return the name given a ZZip entry.">
    <param type="resource" name="zip_entry" />
  </function>
  <function returnType="void" name="zip_close" description="Close a Zip archive.">
    <param type="resource" name="zip" />
  </function>
  <function returnType="int" name="zip_entry_filesize" description="Return the actual filesize of a ZZip entry.">
    <param type="resource" name="zip_entry" />
  </function>
  <function returnType="void" name="zip_entry_close" description="Close a zip entry.">
    <param type="resource" name="zip_ent" />
  </function>
  <function returnType="string" name="zip_entry_read" description="Read X bytes from an opened zip entry.">
    <param type="resource" name="zip_ent" />
    <param optional="true" type="int" name="length" />
  </function>
  <function returnType="resource" castToFalse="true" name="zip_open" description="Open a new zip archive for reading.">
    <param type="string" name="filename" />
  </function>
  <function returnType="bool" name="zip_entry_open" description="Open a Zip File, pointed by the resource entry.">
    <param type="resource" name="zip_dp" />
    <param type="resource" name="zip_entry" />
    <param type="string" name="mode" />
  </function>
  <function returnType="int" name="zip_entry_compressedsize" description="Return the compressed size of a ZZip entry.">
    <param type="resource" name="zip_entry" />
  </function>
  <function returnType="resource" castToFalse="true" name="zip_read" description="Returns the next file in the archive.">
    <param type="resource" name="zip" />
  </function>
</module>

=== d3sformal/weverca/External Sources/PhalangerOriginal/Deployment/TypeDefs/php_iconv.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="array" name="iconv_get_encoding" description="Get internal encoding and output encoding for ob_iconv_handler().">
    <param optional="true" type="string" name="type" />
  </function>
  <function returnType="array" name="iconv_mime_decode_headers" description="Decodes multiple MIME header fields at once.">
    <param type="string" name="encoded_headers" />
    <param optional="true" type="int" name="mode" />
    <param optional="true" type="string" name="charset" />
  </function>
  <function returnType="string" name="iconv_mime_decode" description="Decodes a MIME header field.">
    <param type="string" name="encoded_header" />
    <param optional="true" type="int" name="mode" />
    <param optional="true" type="string" name="charset" />
  </function>
  <function returnType="string" name="iconv_mime_encode" description="Composes a MIME header field.">
    <param type="string" name="field_name" />
    <param type="string" name="field_value" />
    <param optional="true" type="array" name="preferences" />
  </function>
  <function returnType="bool" name="iconv_set_encoding" description="Set current setting for character encoding conversion.">
    <param type="string" name="type" />
    <param type="string" name="charset" />
  </function>
  <function returnType="int" name="iconv_strlen" description="Returns the character count of a string.">
    <param type="string" name="str" />
    <param optional="true" type="string" name="charset" />
  </function>
  <function returnType="int" name="iconv_strpos" description="Finds position of first occurrence of a needle within a haystack.">
    <param type="string" name="haystack" />
    <param type="string" name="needle" />
    <param type="int" name="offset" />
    <param optional="true" type="string" name="charset" />
  </function>
  <function returnType="int" name="iconv_strrpos" description="Finds the last occurrence of a needle within the specified range of haystack.">
    <param type="string" name="haystack" />
    <param type="string" name="needle" />
    <param optional="true" type="string" name="charset" />
  </function>
  <function returnType="string" name="iconv_substr" description="Cut out part of a string.">
    <param type="string" name="str" />
    <param type="int" name="offset" />
    <param optional="true" type="int" name="length" />
    <param optional="true" type="string" name="charset" />
  </function>
  <function returnType="string" name="iconv" description="Returns str converted to the out_charset character set.">
    <param type="string" name="in_charset" />
    <param type="string" name="out_charset" />
    <param type="string" name="str" />
  </function>
  <function returnType="string" name="ob_iconv_handler" description="Returns str in output buffer converted to the iconv.output_encoding character set.">
    <param type="string" name="contents" />
    <param type="int" name="status" />
  </function>
</module>

=== d3sformal/weverca/External Sources/PhalangerOriginal/Deployment/TypeDefs/php_shmop.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="string" name="shmop_read" description="Reads from a shm segment.">
    <param type="int" name="shmid" />
    <param type="int" name="start" />
    <param type="int" name="count" />
  </function>
  <function returnType="int" name="shmop_open" description="Gets and attaches a shared memory segment.">
    <param type="int" name="key" />
    <param type="string" name="flags" />
    <param type="int" name="mode" />
    <param type="int" name="size" />
  </function>
  <function returnType="int" name="shmop_size" description="Returns the shm size.">
    <param type="int" name="shmid" />
  </function>
  <function returnType="void" name="shmop_close" description="Closes a shared memory segment.">
    <param type="int" name="shmid" />
  </function>
  <function returnType="bool" name="shmop_delete" description="Mark segment for deletion.">
    <param type="int" name="shmid" />
  </function>
  <function returnType="int" name="shmop_write" description="Writes to a shared memory segment.">
    <param type="int" name="shmid" />
    <param type="string" name="data" />
    <param type="int" name="offset" />
  </function>
</module>

=== d3sformal/weverca/External Sources/PhalangerSteve/Deployment/TypeDefs/php_dbx.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <function returnType="bool" name="dbx_close">
    <param type="mixed" name="dbx_link" />
  </function>
  <function returnType="mixed" name="dbx_query" description="Returns a dbx_link_object on success and returns 0 on failure.">
    <param type="mixed" name="dbx_link" />
    <param type="string" name="sql_statement" />
    <param optional="true" type="int" name="flags" />
  </function>
  <function returnType="string" name="dbx_error">
    <param type="mixed" name="dbx_link" />
  </function>
  <function returnType="int" name="dbx_compare" description="Returns row_y[columnname] - row_x[columnname], converted to -1, 0 or 1.">
    <param type="array" name="row_x" />
    <param type="array" name="row_y" />
    <param type="string" name="columnname" />
    <param optional="true" type="int" name="flags" />
  </function>
  <function returnType="int" name="dbx_sort" description="Returns 0 on failure, 1 on success.">
    <param type="mixed" name="dbx_result" />
    <param type="string" name="compare_function_name" />
  </function>
  <function returnType="mixed" name="dbx_connect" description="Returns a dbx_link_object on success and returns 0 on failure.">
    <param type="mixed" name="module_name" />
    <param type="string" name="host" />
    <param type="string" name="db" />
    <param type="string" name="username" />
    <param type="string" name="password" />
    <param optional="true" type="bool" name="persistent" />
  </function>
</module>
